[cam_1]
name = "1"
size = [ 1913.79, 1085.758,]
matrix = [ [ 774.534, 0.0, 956.895,], [ 0.0, 773.439, 542.879,], [ 0.0, 0.0, 1.0,],]
distortions = [ 0.015, -0.014, 0.006, -0.003,]
rotation = [ -1.063, -0.052, 0.158,]
translation = [ 1.521, -1.933, 13.932,]
fisheye = false

