[cam_1]
name = "1"
size = [ 1913.79, 1085.758,]
matrix = [ [ 774.534, 0.0, 956.895,], [ 0.0, 773.439, 542.879,], [ 0.0, 0.0, 1.0,],]
distortions = [ 0.015, -0.014, 0.006, -0.003,]
rotation = [ 1.91, 0.679, -0.515,]
translation = [ 0.467, 0.39, 4.282,]
fisheye = false

[cam_2]
name = "2"
size = [ 1913.79, 1085.758,]
matrix = [ [ 774.534, 0.0, 956.895,], [ 0.0, 773.439, 542.879,], [ 0.0, 0.0, 1.0,],]
distortions = [ 0.015, -0.014, 0.006, -0.003,]
rotation = [ 0.904, 2.218, -1.103,]
translation = [ -0.724, -0.216, 4.07,]
fisheye = false

[cam_3]
name = "3"
size = [ 1913.79, 1085.758,]
matrix = [ [ 774.534, 0.0, 956.895,], [ 0.0, 773.439, 542.879,], [ 0.0, 0.0, 1.0,],]
distortions = [ 0.015, -0.014, 0.006, -0.003,]
rotation = [ 1.999, -0.873, 0.57,]
translation = [ -0.984, -0.173, 4.123,]
fisheye = false

[cam_4]
name = "4"
size = [ 1913.79, 1085.758,]
matrix = [ [ 774.534, 0.0, 956.895,], [ 0.0, 773.439, 542.879,], [ 0.0, 0.0, 1.0,],]
distortions = [ 0.015, -0.014, 0.006, -0.003,]
rotation = [ 1.023, -2.202, 1.193,]
translation = [ 0.588, -0.002, 3.976,]
fisheye = false

[metadata]
adjusted = false
error = 0.0
