[cam_1]
name = "1"
size = [ 1913.79, 1085.758,]
matrix = [ [ 774.534, 0.0, 956.895,], [ 0.0, 773.439, 542.879,], [ 0.0, 0.0, 1.0,],]
distortions = [ 0.015, -0.014, 0.006, -0.003,]
rotation = [ -0.93, -0.486, -0.657,]
translation = [ -2.331, 0.569, 7.032,]
fisheye = false

[cam_2]
name = "2"
size = [ 1913.79, 1085.758,]
matrix = [ [ 774.534, 0.0, 956.895,], [ 0.0, 773.439, 542.879,], [ 0.0, 0.0, 1.0,],]
distortions = [ 0.015, -0.014, 0.006, -0.003,]
rotation = [ -0.493, 1.416, 2.233,]
translation = [ -0.827, 2.156, 5.454,]
fisheye = false

[cam_3]
name = "3"
size = [ 1913.79, 1085.758,]
matrix = [ [ 774.534, 0.0, 956.895,], [ 0.0, 773.439, 542.879,], [ 0.0, 0.0, 1.0,],]
distortions = [ 0.015, -0.014, 0.006, -0.003,]
rotation = [ -0.142, -1.284, -2.32,]
translation = [ -1.0, 0.668, 6.479,]
fisheye = false

[cam_4]
name = "4"
size = [ 1913.79, 1085.758,]
matrix = [ [ 774.534, 0.0, 956.895,], [ 0.0, 773.439, 542.879,], [ 0.0, 0.0, 1.0,],]
distortions = [ 0.015, -0.014, 0.006, -0.003,]
rotation = [ -1.078, 0.048, 0.01,]
translation = [ -0.854, 1.06, 6.93,]
fisheye = false

[metadata]
adjusted = false
error = 0.0
